### ISSUE TITLE
[Question] Editor page options have `thumbnail` and `preview`

### ISSUE THREAD

**Issue by ysm0622** [kosslab-kr/gitCodeShare.com#114]
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/18487241/45912397-6d4f1200-be5b-11e8-86bb-7a0871ede9c9.png">

Editor page options have `thumbnail` and `preview`.

1. What exactly `thumbnail` do?

1. How can we implement `preview` option? - by image? or small editor?
- If image, then maybe we have to call image api every user typings.
- If small editor, then it may break consistency between `preview` and real `image`.

@gimdongwoo

**Comment by gimdongwoo** [comment]
@thomasJang Help!

**Comment by thomasJang** [comment]
I prefer a smaller editor than a thumbnail image.
If you use a small editor to capture the image, it will not be a problem.

**Comment by thomasJang** [comment]
I'm SOOO sorry about late an answer
The thumbnail option is just an example of a document.
Option types could not be predicted in planning. Only include items that you can add as an option.

**Comment by ysm0622** [comment]
Thanks.
