### ISSUE TITLE
TIL

### ISSUE THREAD

**Issue by umanking** [kosslab-kr/gitCodeShare.com#125]
![kakaotalk_photo_2018-09-29-17-24-23](https://user-images.githubusercontent.com/28615416/46243213-9d268880-c40c-11e8-8bbb-c6ff559aaa67.jpeg)

I read book nodejs book for the basic ! 

summary (chater 1,2,3 )
- node js feature, single thread, non-blocking I/O
- built-in object global, os, process, ... 
- callback hell --> promiss(resolve, err) -> async/await 
- understanding buffer, stream using (fs module)! 

today evening learning plan 
- using http module, create webser 
- learn express middle ware
- with MYSQL (sequealizer ) ..... maybe it's not ! 

What I feel today
- for me like beginner developer of nodejs, book is powerful more than blogger ! 
it's good for me summary and wrap up !

**Comment by gimdongwoo** [comment]
Goodjob!
