### ISSUE TITLE
[Chrome extension] Which directory should the chrome extension file be in?

### ISSUE THREAD

**Issue by rjs1197** [kosslab-kr/gitCodeShare.com#14]
I saw that chrome extensions should be in one directory. Is this true? If it true, Where should we store Chrome extensions?

How about an octotree's structure? In  octotree case, [octotree/src/config/chrome/](https://github.com/buunguyen/octotree/tree/master/src/config/chrome) has octotree chrome extension code stored.

**Comment by ysm0622** [comment]
Chrome extension files have to compress to zip at real web store publishing time, not local testing time.

See: [https://developer.chrome.com/webstore/publish](https://developer.chrome.com/webstore/publish)
[https://github.com/buunguyen/octotree/tree/master/dist](https://github.com/buunguyen/octotree/tree/master/dist)

That `chrome.zip` file will be publish.

And also they have chrome extension publishing API.

So we can automate publishing our extension with CI tools and github web push hooks.

**Comment by rjs1197** [comment]
Thanks!! Some question has been resolved!

Our project also has a `manifest.json` like octotree, but the actual publishing is through `chrome.zip`. 

If so, the `manifest.json` for the Chrome extension would be okay like octotree? Is it a CI tool's job?

**Comment by ysm0622** [comment]
Try download octotree's [`chrome.zip`](
https://github.com/buunguyen/octotree/blob/master/dist/chrome.zip?raw=true) file and unzip.

You can see `manifest.json` file and other extension scripts.

If we push the extension scripts and `manifest.json`, then CI will publish the extension after clone and compression.

**Comment by rjs1197** [comment]
Thanks for your comments! :D I got it all.
