### ISSUE TITLE
[Chrome-Extension] Button refresh in facebook newsfeed

### ISSUE THREAD

**Issue by rayleighko** [kosslab-kr/gitCodeShare.com#147]
We need to modify the point of calling our button on Facebook.

Now, look like this:

![button](https://user-images.githubusercontent.com/24822072/46567818-268e0b80-c975-11e8-957e-3bd30c9dbda2.gif)

If users are running our program with the Chrome extension, the user will need to press the '...' button and the '...' button again to write.

**Comment by ho1234c** [comment]
I think this issue be solved by doing interval cycle more faster. but It trade off to performance.
