### ISSUE TITLE
[Backend] team study

### ISSUE THREAD

**Issue by umanking** [kosslab-kr/gitCodeShare.com#18]
![kakaotalk_photo_2018-08-19-16-34-37](https://user-images.githubusercontent.com/28615416/44306708-47070400-a3cf-11e8-9b9f-2298450d2748.jpeg)
![kakaotalk_photo_2018-08-19-16-34-42](https://user-images.githubusercontent.com/28615416/44306709-479f9a80-a3cf-11e8-9910-da3ea57dbb43.jpeg)

### This Week
- [x] Project Structuring (models, controllers, config) 
- [x] Extract Gist API  [(reference)](https://developer.github.com/v3/gists/)
- [x] To be contributors
- [x] Develop [sample-project](https://github.com/aeei/express-ts)

### Next Week
- [ ] Analyze puppeteer, carbon
- [ ] Develop Gist API

### Gist API Design

Method | Routes | Description
-- | -- | --
GET | /gists | List of gists
GET | /gists/:gist_id | Get single gists
FETCH | /gists/:gist_id | Edit gists
POST | /gists | Create gists

### Request
Create OAuth app, we need to get `client_id` `client_secret` 
cc. @gimdongwoo @thomasJang

**Comment by thomasJang** [comment]
Good job every one~

**Comment by gimdongwoo** [comment]
Nice yeah~

**Comment by jayjongcheolpark** [comment]
@umanking I think you mean 

PATCH | /gists/:gist_id | Edit gists
-- | -- | --

Is it right?
Nice offline meeting! Great 👍
