### ISSUE TITLE
If the page height is long, the animation will not work.

### ISSUE THREAD

**Issue by thomasJang** [kosslab-kr/gitCodeShare.com#197]
<img width="1892" alt="capture 22" src="https://user-images.githubusercontent.com/5884902/47290273-a1277e00-d639-11e8-8a11-546a4fe91f6e.png">

If the page height is long, the animation will not work.
@likelionWonHo need to check, please.

**Comment by likelionWonHo** [comment]
Solved at PR #214 . Review and test please.
