### ISSUE TITLE
[BackEnd] doesn't work with github.

### ISSUE THREAD

**Issue by rayleighko** [kosslab-kr/gitCodeShare.com#200]
![oct-22-2018 21-25-48](https://user-images.githubusercontent.com/24822072/47292157-1e0a2600-d641-11e8-8fe3-eb0085857fb2.gif)

this Error when  click `SIGNUP WITH GITHUB` button.

Is this working normally? If don't go to the main page with github user information, I will need to rewrite the code for the Chrome extension.

Plz when signin our service with github, send to the main page if users are already signed up.

Could this be because of a problem with github's server today?

**Comment by likelionWonHo** [comment]
Solved now
