### ISSUE TITLE
Secret key management

### ISSUE THREAD

**Issue by aeei** [kosslab-kr/gitCodeShare.com#27]
If there is a key should not be exposed, how can I management and shared with developers?

If I registered key into .gitignore file, I cannot share the key with developers. 
In the opposite case, the key can be exposed.

How should I do?

**Comment by ysm0622** [comment]
Find out [dotenv](https://github.com/motdotla/dotenv/blob/master/README.md) project.

**Comment by umanking** [comment]
I think we should manage secrete-key as a file like .env.example!! [refrence](https://github.com/kosslab-kr/kosscontributhon2018/blob/master/.env.sample)
but it's too dangerous include .env files in source code! 
first, we make `.env.develop ` and `.env.product` files
`.env.develop` files it's ok share with other developers and just test oauth app!!
second, `env.product` file not to be shared with other developers
so we should use private channel like kakaotalk sharing .env.product file!!

**Comment by aeei** [comment]
Through private channel.
Is that an only option for share .env.production file?
