### ISSUE TITLE
[study] What i studied today

### ISSUE THREAD

**Issue by likelionWonHo** [kosslab-kr/gitCodeShare.com#33]
##### React

- [x] state update, delete
- [x] view examples of ajax http request

##### Typescript

- [x] [interface](https://poiemaweb.com/typescript-interface)

      - interface basic
      - duck typing
      - interface optional props => ? behind interface props

- [x] [generic](https://poiemaweb.com/typescript-generic)

      - prevent runtime type error
      - And make type extend scalable at the same time

```typescript

class Parent {
  data:any[];
  
  constructor(){
  	this.data = [];    
  }
  
  push(item) {
  	this.data.push(item);
  }
}

const p = new Parent();
p.push(1);
p.push('1');

p.data = p.data.map(v => v.toFixed()); // type error    

// extend Number type
class Child extends Parent {
  push(item: number) {
    super.push(item);
  }
}

const c = new Child();
c.push(1);
c.push('1');

c.data = c.data.map(v => v.toFixed()); // clean

// but at various type ?
// use generic

class Parent<T> {
  protected data: Array<T> = [];

  push(item) {
    this.data.push(item);
  }
}

const numArr = new Parent<number>();
numArr.push(1);
numArr.push('1') // compile error

const objArr = new Parent<{num: number, str: string}>();
objArr.push({num: '1', str: 1}) // compile error
```

##### To study more

- do stop just take notes, and move to code
- more on typescript
- javascript polymorphism

**Comment by gimdongwoo** [comment]
Good job!
