### ISSUE TITLE
First online meetup

### ISSUE THREAD

**Issue by thomasJang** [kosslab-kr/gitCodeShare.com#40]
<img width="1680" alt="capture 9" src="https://user-images.githubusercontent.com/5884902/44501216-4f10bd80-a6c7-11e8-8748-d578a5db9c8b.png">
<img width="2152" alt="capture 12" src="https://user-images.githubusercontent.com/5884902/44501232-5d5ed980-a6c7-11e8-9233-54ec20a03a4e.png">
<img width="2560" alt="capture 13" src="https://user-images.githubusercontent.com/5884902/44501236-5f289d00-a6c7-11e8-9a3c-f0b7677fe5d8.png">

- At the first meeting, we shared what we studied.
- @gimdongwoo mentor had explained an overview of the project structure.

**Comment by gimdongwoo** [comment]
Good summary!
