### ISSUE TITLE
What I Studied today

### ISSUE THREAD

**Issue by rjs1197** [kosslab-kr/gitCodeShare.com#43]
learn Typescript at [Typescript Handbook for korean](https://infoscis.github.io/2017/05/14/TypeScript-handbook-basic-types/)

also, Today My Team - 'Chrome extension' made an online meeting on 10 pm. - We shared our thoughts on Chrome Extensions. 

> I join to Typescript study group in my community! 

[this is my study group](https://github.com/AUSG/AUSG_Study/tree/master/TypeScript)

```
today's learning time: 1hr
total learning time: 4hr
```

**Comment by gimdongwoo** [comment]
Good job
