### ISSUE TITLE
[Chrome Extension] Team meeting - online(Zoom.us)

### ISSUE THREAD

**Issue by rjs1197** [kosslab-kr/gitCodeShare.com#44]
### Chrome Extension

- Shared experience creating 'Chrome Extension' basic tutorials.**(Myungjin)**
- Explained the contents of the manifest.json file.**(Chris)**
- Explained the structure of the background.js.**(Chris)**
- Shared experience creating facebook pages modification example use 'Chrome Extension'.**(Chris)**

### Typescript

- Explained the difference between Android and Typescript.**(songi)**
- keyword 'generic' in Typescript.**(songi)**

### React

- Explained what should pay attention to when using React.**(Jongho)**
- Explained the difference between MobX and Redux.**(Jongho)**

### Etc.

- We wonder why use MobX, mobx state tree?'**(all)**
- We finally discussed to the features we will develop. but, we decided to proceed  after the next offline meeting to details.**(all)**

![screen shot 2018-08-23 at 22 25 07](https://user-images.githubusercontent.com/24822072/44530461-62547500-a729-11e8-8985-b20c8bb3e88d.png)

**Comment by gimdongwoo** [comment]
Good job!
