### ISSUE TITLE
What I Studied today

### ISSUE THREAD

**Issue by jiniC** [kosslab-kr/gitCodeShare.com#46]
- Watch the [video lecture about Typescript](https://www.inflearn.com/course/%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%BD%94%EB%A6%AC%EC%95%84-1705-%EA%B8%B0%EC%B4%88-%EC%84%B8%EB%AF%B8%EB%82%98/)
(need to study more about the concepts of Class and Generic)
- Let's practice Migrating from JavaScript to TypeScript in a project [To-Do List App](https://github.com/jiniC/TodoListApp)
(setting only on local)

**Comment by gimdongwoo** [comment]
Good job
