### ISSUE TITLE
how about connect travis ci, commit lint ours project ?

### ISSUE THREAD

**Issue by siosio34** [kosslab-kr/gitCodeShare.com#5]
suggest below two lib for more convenient and systematic ours opensource project gitCodeShare! 
- travis ci (https://travis-ci.org/)
```
easliy sync ours github project and test code in convenient.
for example build error, lint error etc... 
```
- commitlint(https://github.com/marionebl/commitlint)

```
commitlint is Lint commit messages.  if use this lib then commit message display According to purpose
for example test: blah blah, ci: blah blah, docs: blah blah 
```

**Comment by gimdongwoo** [comment]
I guess, `circle-ci` is more suitable for our projects.
`commitlint` is interesting. I will review it.

**Comment by siosio34** [comment]
Ok i will study circleci and connect ours project!
and if you end commitlint review please leave comment this issue~

**Comment by gimdongwoo** [comment]
Sorry. I'm late.
You will use your forked repository for C.I testing.

**Comment by siosio34** [comment]
i will close this issue. and concentrate test code and circleci study

**Comment by siosio34** [comment]
if you want commit lint in future. please make issue and pass over me ~
