### ISSUE TITLE
[Backend] Team Meeting - offline

### ISSUE THREAD

**Issue by umanking** [kosslab-kr/gitCodeShare.com#53]
![kakaotalk_photo_2018-08-26-15-08-23](https://user-images.githubusercontent.com/28615416/44625351-e5e8ae80-a941-11e8-8066-b5b0ef33d6ff.jpeg)

### This week
- stuck in the passport.js
- [problem] passport doesn’t verify callback function never called
- [problem] Also, serialize/deserialize is not working

### Next week
- study puppeteer

**Comment by gimdongwoo** [comment]
Awesome!
