### ISSUE TITLE
Chrome extension popup file must be a static HTML file.

### ISSUE THREAD

**Issue by ysm-dev** [kosslab-kr/gitCodeShare.com#57]
![image](https://user-images.githubusercontent.com/18487241/44617234-31e01880-a89a-11e8-9b9f-234860d715b2.png)

Chrome extension popup file must be a static HTML file.

So I think we have two options.

1. Generate popup.html file through like `next export` command and include in chrome extension folder.

1. Use `iframe` tag like `<iframe src="{ server_url }/popup">` to also server-side render for popup.
   (Ref : [https://stackoverflow.com/questions/40608175/render-chrome-extension-popup-ui-dynamically](https://stackoverflow.com/questions/40608175/render-chrome-extension-popup-ui-dynamically))

Which one is the better solution?

**Comment by gimdongwoo** [comment]
Nice catch.
I think before. We can use `next build & next export` for static html.
https://nextjs.org/docs#static-html-export
