### ISSUE TITLE
2th Online Meeting with zoom.us

### ISSUE THREAD

**Issue by thomasJang** [kosslab-kr/gitCodeShare.com#60]
<img width="2560" alt="capture 14" src="https://user-images.githubusercontent.com/5884902/44696113-23b81500-aab1-11e8-85e7-13ed23fd351e.png">
<img width="2560" alt="capture 15" src="https://user-images.githubusercontent.com/5884902/44696114-23b81500-aab1-11e8-9561-c042dc3ae5d7.png">
<img width="2560" alt="capture 16" src="https://user-images.githubusercontent.com/5884902/44696115-2450ab80-aab1-11e8-888a-c9220cc16c7f.png">

- Shared what we studied.
- @gimdongwoo mentor reviewed 'carbon' project. The 'carbon' project has a lot to reference point.

**Comment by gimdongwoo** [comment]
Nice yeah~
