### ISSUE TITLE
[Frontend] team offline meet-up

### ISSUE THREAD

**Issue by thomasJang** [kosslab-kr/gitCodeShare.com#73]
![image](https://user-images.githubusercontent.com/5884902/45138691-4dc3b280-b1e8-11e8-8d90-f94b09a23c4d.png)

Last night we studied `MST`,` mobx`, and `React`.
As a result, we created 'AppStore'. It consists of 'spinning, alert, load' and can be used at any time in the subcomponent.

**Comment by gimdongwoo** [comment]
![img_7317](https://user-images.githubusercontent.com/7310854/47650795-af8b1200-dbc4-11e8-9d89-7d6ec6d22486.jpg)
![img_7307](https://user-images.githubusercontent.com/7310854/47650797-b023a880-dbc4-11e8-8169-90ccf19e1975.jpg)
![img_7306](https://user-images.githubusercontent.com/7310854/47650798-b023a880-dbc4-11e8-8fec-0afa368515ed.jpg)
