### ISSUE TITLE
[Error] I fail to build 

### ISSUE THREAD

**Issue by rjs1197** [kosslab-kr/gitCodeShare.com#76]
I failed to build today. because I fail to `npm i` command in terminal. follow error messages to detail:

```
> Failed to build
{ Error: (server) /Users/rayleigh/Development/gitCodeShare.com/stores/AppStore.ts
ERROR in /Users/rayleigh/Development/gitCodeShare.com/stores/AppStore.ts(2,25):
...
...
errors: [ '(server) 
/Users/rayleigh/Development/gitCodeShare.com/stores/AppStore.ts\n\u001b[1m\u001b[31mERROR 
in\u001b[39m\u001b[22m\u001b[1m\u001b[36m/Users/rayleigh/Development/gitCodeShare.com/
stores/AppStore.ts(2,25)\u001b[39m\u001b[22m\u001b[1m\u001b[31m:\u001b[39m\u001b[22m\
n\u001b[90mTS2307: \u001b[39mCannot find module \'../providers/ApiProvider\'.' ],
```

I tried to fix it. However, I didn't know the contents of 'proviers/ApiProvider.ts' and gave up. Who will tell me the contents of this file?

**Comment by likelionWonHo** [comment]
The ApiStore requires a provider that primarily uses asynchronous requests, such as authentication. But it's not yet reflected in the code. Tomorrow the frontend team will ask for a pull request.

**Comment by thomasJang** [comment]
Fixed now. https://github.com/kosslab-kr/gitCodeShare.com/pull/77
