### ISSUE TITLE
[Solved] prettier conflicts with beautify

### ISSUE THREAD

**Issue by likelionWonHo** [kosslab-kr/gitCodeShare.com#79]
I was using beautify before using prettier and it seemed to work well for a while.
However, immediately after that, I realized that storing jsx in js would always cause breaking.
I did not find a cause for it, but it turned out to be conflict between prettier and beautify.

#### Expected
<img width="650" alt="2018-09-07 2 01 41" src="https://user-images.githubusercontent.com/18139217/45173052-0a962d80-b242-11e8-9be3-5255060b6788.png">

#### Actual
<img width="400" alt="2018-09-07 2 03 03" src="https://user-images.githubusercontent.com/18139217/45173108-2dc0dd00-b242-11e8-9ffe-ceea9f7f9c5b.png">

The best way is to remove the beautify of duplicate personality.
But if you want to use it at the same time in other code like html, css, else, add one to your user settings.
```JSON
"beautify.ignore": [
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
 ]
```

**Comment by gimdongwoo** [comment]
If you use the VSCode and the Prettier, and you use `.js` to React.
This helps you.

```
"files.associations": {
        "*.js": "javascriptreact"
    },
```
