### ISSUE TITLE
[Study] What i studied today

### ISSUE THREAD

**Issue by likelionWonHo** [kosslab-kr/gitCodeShare.com#8]
##### React tutorial

- [x] [Props and state in react]( https://react-anyone.vlpt.us/04.html )

- [x] [Life cycle in react](https://react-anyone.vlpt.us/05.html)

- [x] [Data rendering, add, delete in component](https://velopert.com/3636)

- [x] [Why state immutability is critical in react?](https://velopert.com/3640)

##### Typescript tutorial

- [x] [Variable type, return type of typescript](https://poiemaweb.com/typescript-typing)

- [ ] [Class in typescript](https://poiemaweb.com/typescript-class)

##### Setting

- [ ] make personal repo for study and commit code

#### Next planned

- Data update in react
- typescript interface
- make personal github repo for study

**Comment by gimdongwoo** [comment]
Good job!
