### ISSUE TITLE
[Chrome-Extension] We need to use the HTTPS protocol in our development environment.

### ISSUE THREAD

**Issue by rjs1197** [kosslab-kr/gitCodeShare.com#89]
We thought our service should also use **`https`** in the development environment.

Because, Facebook use **`https`** protocol. so, if we use **`http`**, our code will not work properly.

But, we thought that it wasn't always easy to use **`https`** on localhost's protocol. so, we need to get some feedback this please.

We think our product might be able to use the **`proxy`** now. please let me know if you have any comments on this.

**Comment by ho1234c** [comment]
if we made key file for localhost test, how should we manage key file..? It needs to be accessible to everyone contribute to this project. but key file should be don't reveal in essence. let me know if you have any ideas!

**Comment by siosio34** [comment]
i made google drive share link for key and cert file and shared env filelist before project. i think that not bad solution~

**Comment by ysm0622** [comment]
There's a solution for development env.

<img width="145" alt="image" src="https://user-images.githubusercontent.com/18487241/46530512-f4c56800-c8d4-11e8-917b-110854b36aae.png">

Click `shield`🛡 icon at the right end of address bar in browser, and click `Load Unsafe Scripts`.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/18487241/46530564-1f172580-c8d5-11e8-9f10-8e2811d1a182.png">

Now you allowed `mixed content` and the site become insecure mode.

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/18487241/46530609-479f1f80-c8d5-11e8-838e-79b25a01e863.png">

It's for only development env.

**Comment by rjs1197** [comment]
Done!
